### ISSUE TITLE
[Bug]: App crash due to int conversion and comparison against empty field.

### ISSUE THREAD

**Issue by paljsingh** [paljsingh/impartus-downloader#100]
Traceback (most recent call last):
  File "C:\Users\arund\impartus-downloader\ui\uiitems\table.py", line 304, in on_click_download_video
    row = self.get_row_from_rfid(rf_id, is_flipped)
  File "C:\Users\arund\impartus-downloader\ui\uiitems\table.py", line 543, in get_row_from_rfid
    if int(self.table.item(i, fcid_col_index).text()) == rf_id:
ValueError: invalid literal for int() with base 10: ''

**Comment by paljsingh** [comment]
The issue should be appearing for all flipped lecture downloads,
as well as non-flipped/regular lectures that appear below a flipped lecture in the table.
Fixed with commit #61a0178
