### ISSUE TITLE
None of the video downloads work

### ISSUE THREAD

**Issue by devmalya-b** [paljsingh/impartus-downloader#109]
Everytime I try to download using the UI, the promt puts up this error:

`Traceback (most recent call last):
  File "D:\D\Assignments\venv\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\D\Assignments\venv\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\rocke\anaconda3\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\rocke\anaconda3\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\rocke\anaconda3\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\rocke\anaconda3\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\rocke\anaconda3\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\rocke\anaconda3\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out`

And then this has multiple traceback loops to other issues, the last one of them being:

`Traceback (most recent call last):
  File "D:\D\Assignments\impartus-downloader\ui\helpers\worker.py", line 20, in run
    self.status = self.task()
  File "D:\D\Assignments\impartus-downloader\ui\uiitems\videos.py", line 76, in _download_video
    return self.impartus.process_video(
  File "D:\D\Assignments\impartus-downloader\lib\core\impartus.py", line 113, in process_video
    m3u8_content = self.download_m3u8_regular(rf_id)
  File "D:\D\Assignments\impartus-downloader\lib\core\impartus.py", line 74, in download_m3u8_regular
    m3u8_urls = self._download_m3u8(master_url)
  File "D:\D\Assignments\impartus-downloader\lib\core\impartus.py", line 61, in _download_m3u8
    response = self.session.get(master_url, timeout=self.timeouts)
  File "D:\D\Assignments\venv\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\D\Assignments\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\D\Assignments\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\D\Assignments\venv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='a.impartus.com', port=443): Max retries exceeded with url: /api/fetchvideo?ttid=8657375&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NTM5NTU2LCJldWxhIjoxLCJpbnN0aXR1dGVJZCI6MTI4LCJ1c2VyVHlwZSI6NiwiaWF0IjoxNjgzNjQyNjQ3LCJleHAiOjE2ODQyNDc0NDd9.S6otqGzcI6LDuKv5n5OALar5mPquk4VDIK1WW3caoVE&type=index.m3u8 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='a.impartus.com', port=443): Read timed out. (read timeout=5.0)"))`

I assume the video can't be fetched from impartus? if so, why is that and how do I solve it? I have reinstalled the source many times and even made sure that the impartus server isn't down.

**Comment by paljsingh** [comment]
A read timeout could be due to the server being down for the time being, or connections being throttled.
Were you able to download the videos at any other point in time?
