### ISSUE TITLE
Invalid Syntax error with python v3.5

### ISSUE THREAD

**Issue by paljsingh** [paljsingh/impartus-downloader#28]
![image](https://user-images.githubusercontent.com/5433003/114275886-e0342e80-9a41-11eb-89c0-036311ef967e.png)

**Comment by paljsingh** [comment]
Confirmed, that tksheet won't run wit python3.5

$ docker pull davidjfelix/python3.5
...

$ docker run --rm -it --name python35 davidjfelix/python3.5 /bin/bash

---
tksheet installs fine with python3.5 without issues.

root@075ee9d2111f:/# pip3 install tksheet
You are using pip version 7.1.0, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting tksheet
  Downloading https://files.pythonhosted.org/packages/49/94/b46edf6f489ca721d843e9601427c05c653261a8f80d6fff41d9dee53dd3/tksheet-5.0.21.tar.gz (74kB)
    100% |████████████████████████████████| 77kB 1.2MB/s
Installing collected packages: tksheet
  Running setup.py install for tksheet
Successfully installed tksheet-5.0.21

---
but fails when importing.

root@075ee9d2111f:/# echo 'import tksheet' >>  test.py

root@075ee9d2111f:/# python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import tksheet
  File "/usr/local/lib/python3.5/site-packages/tksheet/__init__.py", line 1, in <module>
    from ._tksheet_column_headers import ColumnHeaders
  File "/usr/local/lib/python3.5/site-packages/tksheet/_tksheet_column_headers.py", line 696
    hw = self.MT.GetHdrTextWidth(f"{data_col + 1}") + 5
                                                 ^
SyntaxError: invalid syntax

**Comment by paljsingh** [comment]
Updated README to mention that the app would require python version >= 3.6
