### ISSUE TITLE
[Bug]: Invalid format error while getting the epoch value

### ISSUE THREAD

**Issue by brahma19** [paljsingh/impartus-downloader#66]
**Describe the bug**
strftime('%s') is deprecated and it throws the invalid format error on python 3.7.10.
To get the epochtime we can use timestamp() from datetimetime object.
https://github.com/paljsingh/impartus-downloader/blob/master/ui/content.py#L502

**To Reproduce**
1. Run the App

**Expected behavior**

**Error Stack**
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\<>\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\<>\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\<>\Documents\impartus_downloader\idm\ui\content.py", line 533, in _download_video
    self.save_captions_if_needed(video_metadata, root_url, captions_path)
  File "C:\Users\<>\Documents\impartus_downloader\idm\ui\content.py", line 502, in save_captions_if_needed
    start_epoch = int(datetime.strptime(video_metadata['startTime'], date_format).strftime('%s'))
ValueError: Invalid format string

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Python Version 3.7.10

**Additional context**

**Comment by brahma19** [comment]
changing this line  int(datetime.strptime(video_metadata['startTime'], date_format).strftime('%s'))
https://github.com/paljsingh/impartus-downloader/blob/master/ui/content.py#L502
to below is working as expected
datetime.strptime(video_metadata['startTime'], date_format).timestamp()

**Comment by paljsingh** [comment]
@brahma19 
Thanks for reporting the issue,
This is fixed in v3.5.1
Please let me know if you see any issues.
