### ISSUE TITLE
[Bug]: tksheet version issue

### ISSUE THREAD

**Issue by brahma19** [paljsingh/impartus-downloader#67]
**Describe the bug**
new version of tksheet published on 11th June is breaking the module.

**To Reproduce**
1. install dependencies 
2. Run the app

**Screenshot**
![image](https://user-images.githubusercontent.com/59507487/121774705-456ee200-cba1-11eb-8cd9-10e6da35127d.png)

**Error Stack**
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\<>\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\<>\Documents\impartus_downloader\idm\ui\content.py", line 900, in show_video_callback
    self.set_display_widgets()
  File "C:\Users\<>\Documents\impartus_downloader\idm\ui\content.py", line 145, in set_display_widgets
    self.fill_content()
  File "C:\Users\<>\Documents\impartus_downloader\idm\ui\content.py", line 460, in fill_content
    self._init_content()
  File "C:\Users\<>\Documents\impartus_downloader\idm\ui\content.py", line 98, in _init_content
    self.set_display_columns()
  File "C:\Users\<>\Documents\impartus_downloader\idm\ui\content.py", line 735, in set_display_columns
    self.sheet.display_columns(indexes=column_states, enable=True, redraw=False)
  File "C:\Users\<>\AppData\Local\Programs\Python\Python37\lib\site-packages\tksheet\_tksheet.py", line 2156, in display_columns
    return self.displayed_columns(indexes = indexes, enable = enable, reset_col_positions = reset_col_positions, set_col_positions = set_col_positions, refresh = refresh, redraw = redraw, deselect_all = deselect_all)
  File "C:\Users\<>\AppData\Local\Programs\Python\Python37\lib\site-packages\tksheet\_tksheet.py", line 2147, in displayed_columns
    deselect_all = deselect_all)
  File "C:\Users\<>\AppData\Local\Programs\Python\Python37\lib\site-packages\tksheet\_tksheet_main_table.py", line 3333, in display_columns
    if enable and list(range(len(max(self.data_ref, key = len)))) != self.displayed_columns:
ValueError: max() arg is an empty sequence`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version : 3.7.10

**Additional context**

**Comment by brahma19** [comment]
uninstalled tksheet 5.0.27 and installed 5.0.25 and it is working fine.
pip install tksheet==5.0.25

Need to add the version in the requirement.txt

**Comment by paljsingh** [comment]
@brahma19 
Thanks for reporting the issue,
I've pushed a new release v3.5.1 with tksheet==5.0.25
